global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: telegram
  routes:
    - receiver: matrix
      matchers:
        - severity=~"info|warning|critical"
      continue: true

    - receiver: telegram
      matchers:
        - severity=~"info|warning|critical"

receivers:
  - name: telegram
    telegram_configs:
      - bot_token_file: /run/secrets/telegram_bot_token
        chat_id_file: /run/secrets/telegram_chat_id
        send_resolved: true

  - name: matrix
    webhook_configs:
      - url: http://matrix-receiver:12345/alerts/pager
        send_resolved: true

